---
- name: "Setup Pi"
  hosts: localhost
  vars_files:
    - smarthome_config.yml
  roles:
    - role: show-facts
    - role: basic-setup
    - role: postfix-with-gmail
    - role: webmin
    - role: portainer
    - role: influx
    - role: grafana
    - role: iobroker
    - role: dokuwiki
    - role: unifi-controller

