---
- name: "Setup Grafana"
  vars:
    block_name: "IOBroker"
  block:
    - name: "Setup basic files and folders"
      include_role:
        name: basic-docker
      vars:
        container_name: "{{ block_name }}"
    - name: "Copy  compose-file to {{ docker.compose_dir }}/{{ block_name }}/docker-compose.yml"
      copy:
        src: "files/docker-compose.yml"
        dest: "{{ docker.compose_dir }}/{{ block_name }}/docker-compose.yml"
        owner: "{{ home_user }}"
        group: "{{ home_user }}"

    - name: "Start Container and wait for readiness"
      include_role:
        name: basic-docker-compose-up
      vars:
        compose_dir: "{{ docker.compose_dir }}/{{ block_name }}"
        health_check: "http://localhost:8081/"




