---
- name: "Setup Grafana"
  vars:
    container_name: "IOBroker"
  block:
    - name: "Setup basic files and folders"
      include_role:
        name: basic-docker
      vars:
        role_container_name: "{{ container_name }}"
    - name: "Copy  compose-file to {{ docker_compose_dir }}/{{ container_name }}/docker-compose.yml"
      copy:
        src: "files/docker-compose.yml"
        dest: "{{ docker_compose_dir }}/{{ container_name }}/docker-compose.yml"
        owner: "{{ smart_home_user }}"
        group: "{{ smart_home_user }}"

    - name: "Start Container and wait for readiness"
      include_role:
        name: basic-docker-compose-up
      vars:
        role_compose_dir: "{{ docker_compose_dir }}/{{ container_name }}"
        role_health_check: "http://localhost:8081/"




