---
- name: "Get UID for User {{ smart_home_user }}"
  shell: "id -u {{ smart_home_user }}"
  register: user_id
  changed_when: false

- name: "Get GID for User {{ smart_home_user  }}"
  shell: "id -g {{ smart_home_user  }}"
  register: group_id
  changed_when: false
