---
version: "3.5"
services:
  iobroker:
    restart: always
    image: buanet/iobroker
    hostname: iobroker.docker
    extra_hosts:
      - ${HOST_NAME}:${HOST_IP}
      - ${HOST_NAME_FULL}:${HOST_IP}
    container_name: IOBroker
#    devices:
#      - /dev/ttyAMA0:/dev/ttyAMA0
#      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - PACKAGES=vim net-tools nfs-common cifs-utils
      - ADMINPORT=8081
#      - USBDEVICES=/dev/ttyAMA0;/dev/ttyACM0
    privileged: true
    healthcheck:
      test: curl --fail -s http://localhost:8087/get/system.adapter.admin.0.alive || exit 1
      interval: 3m
      timeout: 5s
      retries: 10
    ports:
      - 8081:8081 # Admin-Adapter
      - 8082:8082 # WebServer VIS und Float
      - 8087:8087 # Simple-Api für Health-Check with 3rd pary tool
      - 1880:1880 # Node Red
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq:/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq:ro
      - ${DOCKER_VOLUMES_BASE}/IOBroker/opt/iobroker:/opt/iobroker
      - ${DOCKER_VOLUMES_BASE}/IOBroker/history:/history
