---
# role_container_name is set with the var-part of "include_role"

- name: "Create directories owned by root (persistent root for docker and backup)"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ smart_home_data_dir }}"
    - "{{ smart_home_backup_dir }}"

- name: "Create persistence directory for container {{ smart_home_data_dir }}/{{ role_container_name }}"
  file:
    path: "{{ smart_home_data_dir }}/{{ role_container_name }}"
    state: directory
    owner: "{{ smart_home_user }}"
    group: "{{ smart_home_user }}"


- name: "Create needed Directories owned by {{ smart_home_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ smart_home_user }}"
    group: "{{ smart_home_user }}"
  loop:
    - "{{ docker_compose_dir }}"

- name: "Add environment-file for alle docker-compose stacks"
  template:
    src: templates/docker.env.j2
    dest: "{{ docker_environment_file }}"

- name: "Create docker-compose directory for container  {{ docker_compose_dir }}/{{ role_container_name }}"
  file:
    path: "{{ docker_compose_dir }}/{{ role_container_name }}"
    state: directory
    owner: "{{ smart_home_user }}"
    group: "{{ smart_home_user }}"

- name: "Create link to global docker-env-file {{ docker_compose_dir }}/{{ role_container_name }}/.env to {{ docker_compose_dir }}/docker.env"
  file:
    src: "{{ docker_compose_dir }}/docker.env"
    dest: "{{ docker_compose_dir }}/{{ role_container_name }}/.env"
    state: link

