---
# role_container_name is set with the var-part of "include_role"

#- name: "Create directories owned by root (persistent root for docker and backup)"
#  file:
#    path: "{{ item }}"
#    state: directory
#    owner: root
#    group: root
#  loop:
#    - "{{ smart_home_data_dir }}"
#    - "{{ smart_home_backup_dir }}"


- name: "Create needed Directories owned by {{ smart_home_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ smart_home_user }}"
    group: "{{ smart_home_user }}"
    mode: "ug+rwx,o-w+rx"
  loop:
    - "{{ smart_home_data_dir }}"
    - "{{ smart_home_backup_dir }}"
    - "{{ smart_home_data_dir }}/{{ role_container_name }}"
    - "{{ smart_home_container_dir }}"
    - "{{ smart_home_container_dir }}/{{ role_container_name }}"

- name: "Add environment-file for all docker-compose stacks"
  template:
    src: templates/docker.env.j2
    dest: "{{ smart_home_container_dir }}/docker.env"

- name: "Create link to global docker-env-file {{ smart_home_container_dir }}/{{ role_container_name }}/.env -> {{ smart_home_container_dir }}/docker.env"
  file:
    src: "{{ smart_home_container_dir }}/docker.env"
    dest: "{{ smart_home_container_dir }}/{{ role_container_name }}/.env"
    state: link

