---

- name: "--------------------- Configuration --------------------------------"
  debug:
    msg:
      - "Architecture: {{ ansible_architecture }} "
      - "Os:           {{ ansible_os_family  }} "
      - "Apt-Packages: {{ apt_packages }} "
      - "Smarthome-User / Docker-User: {{ smart_home_user }}"
      - "Smarthome Root        {{ smart_home_root }}"
      - "Smarthome Basedir     {{ smart_home_container_dir }}"
      - "Smarthome Datadir     {{ smart_home_data_dir }}"
      - "Smarthome Backupdir   {{ smart_home_backup_dir }}"
      - "Smarthome Restoredir  {{ smart_home_restore_dir }}"
      - "Docker-Compose-Dir    {{ smart_home_container_dir }} "
      - "Docker-Env-File       {{ smart_home_container_dir }}/docker.env"
      - "Smarthome-Scripts-Dir: {{ smart_home_script_dir  }}"
      - "Ip-Address: {{ ansible_default_ipv4.address }}"
      - "Host Name: {{ansible_hostname}}  - {{ ansible_dns.domain }} "



