# See https://webmin.com/deb.html
---
- name: "Download and add GPG key with which the repository is signed"
  apt_key:
    url: https://download.webmin.com/jcameron-key.asc
    state: present

- name: "Add apt-Repository for Webmin"
  apt_repository:
    repo: deb https://download.webmin.com/download/repository sarge contrib
    state: present

- name: "Update apt and install apt-transport-https"
  apt:
    update_cache: yes
    name: "apt-transport-https"

- name: "Update apt and install webmin"
  apt:
    update_cache: yes
    name: "webmin"

- name: "Disable https to prevent certificate warnings (see https://doxfer.webmin.com/Webmin/Securing_Webmin)"
  lineinfile:
    path: /etc/webmin/miniserv.conf
    # The String to Search
    regexp: "ssl=1"
    # The String to Replace
    line: "ssl=0"
    state: present
    backup: yes

- name: "Configure Webmin to update all packages and notify you"
  template:
    src: templates/package_config.j2
    dest: /etc/webmin/package-updates/config
    force: true

- name: "Restart webmin"
  systemd:
    name: webmin
    state: restarted

- name: "Waiting for Webmin"
  uri:
    url: "http://localhost:10000"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1


